scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backoffice_backend'
    scrape_interval: 5s
    static_configs:
      - targets: ['domingollanes-shop_saas-backoffice_backend-nginx:80']

  - job_name: 'backoffice_frontend'
    scrape_interval: 5s
    static_configs:
      - targets: ['domingollanes-shop_saas-backoffice_frontend-nginx:80']

  - job_name: 'mooc_backend'
    scrape_interval: 5s
    static_configs:
      - targets: ['domingollanes-shop_saas-mooc_backend-nginx:80']
