# Register an user
POST localhost:8040/auth/register
Content-Type: application/json

{
  "username": "user_test",
  "password": "test"
}

###
# Login an user
POST localhost:8040/auth/login
Content-Type: application/json

{
  "username": "user_test",
  "password": "test"
}

###
