courses_get:
  path: /courses
  controller: ShopSaas\Apps\Backoffice\Frontend\Controller\Courses\CoursesGetWebController
  methods:  [GET]

courses_post:
  path: /courses
  controller: ShopSaas\Apps\Backoffice\Frontend\Controller\Courses\CoursesPostWebController
  methods:  [POST]
